#!/usr/bin/env ruby

# random_password.rb
# generate a random string of 12 alphanumeric characters
# Steven Wilkin @stevebiscuit

chars = ('0'..'9').to_a + ('A'..'Z').to_a + ('a'..'z').to_a

12.times {print chars[rand(chars.length)]}
puts