#!/bin/bash
#
# This is an example of using HGEDITOR to create of diff to review the
# changes while commiting.

# If you want to pass your favourite editor some other parameters
# only for Mercurial, modify this:
case "${EDITOR}" in
    "")
        EDITOR="vi"
        ;;
    emacs)
        EDITOR="$EDITOR -nw"
        ;;
    gvim|vim)
        EDITOR="$EDITOR -f -o"
        ;;
esac


SVNTMP=""
cleanup_exit() {
    rm -rf "$SVNTMP"
}

# Remove temporary files even if we get interrupted
trap "cleanup_exit" 0 # normal exit
trap "exit 255" 1 2 3 6 15 # HUP INT QUIT ABRT TERM

SVNTMP="${TMPDIR-/tmp}/svneditor.$RANDOM.$RANDOM.$RANDOM.$$"
(umask 077 && mkdir "$SVNTMP") || {
    echo "Could not create temporary directory! Exiting." 1>&2
    exit 1
}

(
    grep '^M ' "$1" | cut -b 6- | while read changed; do
        svn diff "$changed" >> "$SVNTMP/diff"
    done
)

cat "$1" > "$SVNTMP/msg"

MD5=$(which md5sum 2>/dev/null) || \
    MD5=$(which md5 2>/dev/null)
[ -x "${MD5}" ] && CHECKSUM=`${MD5} "$SVNTMP/msg"`
if [ -s "$SVNTMP/diff" ]; then
    vim "+e $SVNTMP/diff" '+set buftype=help filetype=diff' "+vsplit $SVNTMP/msg" || exit $?
else
    $EDITOR "$SVNTMP/msg" || exit $?
fi
[ -x "${MD5}" ] && (echo "$CHECKSUM" | ${MD5} -c >/dev/null 2>&1 && exit 13)

mv "$SVNTMP/msg" "$1"

exit $?
